
spring:
  config:
    activate:
      on-profile: qa


build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank accounts related local APIs-qa"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345